### ISSUE TITLE
Receiving 4xx Errors When Submitting Files from TeamCity Builds

### ISSUE THREAD

**Issue by lthuynh** [OPSWAT/metadefender-teamcity-plugin#1]
- We have followed the instructions from here to the "T":          https://www.opswat.com/free-tools/teamcity-plugin
- The version downloaded and installed is:   1.0.0.46 
- It is configured as per the instructions provided by the above page with our API key.
- And we have added these settings to the key build jobs we wish to submit for scanning:
`system.metadefender_scan_artifact=1`
`system.metadefender_fail_build =0`

The plugin does not seem to be working properly, however, as each artifact submission returns with a 4xx error.

![Screen Shot 2021-02-05 at 3 13 18 PM](https://user-images.githubusercontent.com/5567312/107089733-bdc53100-67c4-11eb-8231-2dc1043c74b9.png)

![Screen Shot 2021-02-05 at 3 15 45 PM](https://user-images.githubusercontent.com/5567312/107089970-1e546e00-67c5-11eb-8f40-9550bb85d71e.png)

![image001](https://user-images.githubusercontent.com/5567312/107090421-ce29db80-67c5-11eb-8aef-b905f9001f1f.png)

![image002](https://user-images.githubusercontent.com/5567312/107090435-d2ee8f80-67c5-11eb-9dd1-5875c8a809c4.png)

**Comment by vladoros** [comment]
Hello @lthuynh
Should be fixed via [2d855a4](https://github.com/OPSWAT/metadefender-teamcity-plugin/commit/2d855a4083e53cdfe7b44d1f62340728b1d7b6d8) which also [updates the readme about TeamCity 2020 CRSF protection](https://github.com/OPSWAT/metadefender-teamcity-plugin#teamcity-2020-crsf-protection) (more details on that [here](https://www.jetbrains.com/help/teamcity/csrf-protection.html#Troubleshooting)).
Also, make sure to use [https://api.metadefender.com/v4/file](https://api.metadefender.com/v4/file) as MetaDefender URL since v2 has been [deprecated](https://www.opswat.com/de/blog/metadefender-cloud-api-deprecation).
Please test with the [latest release](https://github.com/OPSWAT/metadefender-teamcity-plugin/releases/tag/1.0.0.48) & feel free to reopen in case of problems.
Thanks for reporting the issue!

**Comment by lthuynh** [comment]
Hi Vlad,
We actually already had these set:
		
teamcity.csrf.paranoid=false
teamcity.csrf.origin.check.enabled=logOnly

Will download the newest version and see if it’s failing.
-Lewis
